django-treebeard/django-treebeard

- treebeard/forms.py
http://code.tabo.pe/django-treebeard/issue/77/movenodeform__init__-method-bypasses
> Fix MoveNodeForm constructor

- treebeard/admin.py
When the the context processor for inserting `request` into the Context is not present in TEMPLATE_CONTEXT_PROCESSORS, `{% result_tree ... %}` will fail because `request` will resolve to `''` and then will end up doing `AttributeError: 'str' object has no attribute 'path'` when trying to insert data into `headers` (and also when returning)
> Prevent the changelist causing an exception

- treebeard/templatetags/admin_tree.py
because `django.contrib.admin.util` became `django.contrib.admin.utils`
> Fixed ImportError in `admin_tree` occurring in current Django `master` 

- treebeard/admin.py
get_urls function:
* Using list instead patterns function
* importing Django javascript_catalog instead of using string name
> compability with Django 1.10

- tox.ini
- treebeard/admin.py
- treebeard/forms.py
- treebeard/templates/admin/tree_change_list_results.html
- treebeard/tests/settings.py
- treebeard/tests/urls.py
This PR includes several changes to make django-treebeard compatible with Django
1.10 while maintaining compatibility with older versions back to 1.7:
* Do not load templatetag  `cycle` from `future`.
* Search request context processor in settings.TEMPLATES.
* Add basic settings.TEMPLATES for tests.
* Replace django.conf.urls.patterns with lists.
* Add separate tox environments for Django 1.9 and 1.10.
> Django 1.10 compatibility.

- .travis.yml
- appveyor.yml
- requirements_test.txt
- tox.ini
- treebeard/mp_tree.py
- treebeard/tests/settings.py
This PR updates the way the tests are run on tox, travis and appveyor.
The database engine is now part of the tox environment string, and the database drivers are now installed via tox so that only the required ones are installed. This is required since installing some drivers on appveyor don't work.
Also the mssql engine is added and the changes from #54 so that the mssql tests now pass.
See https://ci.appveyor.com/project/mvantellingen/django-treebeard/build/1.0.41
> Update test infrastructure

- MANIFEST.in
This makes the tarballs on PyPi suitable for distribution packages again. The
Debian package would otherwise not be able to provide a documentation package.
> Include documentation in source tarball.

- CHANGES
sphinx complains when a title underline is shorter than the text above it. This
fixes the "WARNING: Title underline too short." messages when building the
documentation.
> Fix warnings about too short underlines

- treebeard/admin.py
`django.views.i18n.javascript_catalog` to deprecated in Django 1.10 and removed in 2.0.
> Use django.views.i18n.JavaScriptCatalog on Django >= 1.10

- treebeard/templatetags/admin_tree.py
- `repr` will produce different strings on PY2/3
- Proper JSON encoding doesn't work because string needs to be single quoted due in
double quoted html attribute
Fixes #72
> Use explicit single quotes for result_id

- AUTHORS
- CHANGES
- treebeard/admin.py
Bugfix for "jsi18n" loading in admin change list view.
See:
* https://github.com/django-treebeard/django-treebeard/issues/90
* https://github.com/django-treebeard/django-treebeard/pull/88
> Bugfix issues #90 admin change list view and jsi18n load for Django-1.11

- docs/source/index.rst
- docs/source/install.rst
Support for Django 1.7 was removed in version 4.1.0 (Nov 24, 2016). Update the docs to mention 1.8+ is supported.
> Update supported Django versions in docs

- README.rst
- docs/source/install.rst
- docs/source/tutorial.rst
For details on the new PyPI, see the blog post:
https://pythoninsider.blogspot.ca/2018/04/new-pypi-launched-legacy-pypi-shutting.html
> Update all pypi.python.org URLs to pypi.org

- docs/source/tutorial.rst
As spelled on https://pypi.org/.
> Correct capitalization of PyPI

- treebeard/templates/admin/tree_change_list_results.html
variable named incorrectly, drag and drop does not work in admin in current treebeard versions
> fix drag/drop order not working

- treebeard/forms.py
This will play more nicely with other form classes, that implement `__init__(self, *args, **kwargs)`, e.g. django-parler's `TranslatableModelForm`, where `kwargs.get('instance')` is `None` when called from here as it is passed as `args[8]`. The `BaseModelForm` will still work fine.
> Pass kwargs to super as kwargs, not args

- treebeard/mp_tree.py
Hi! We noticed that calling `get_ancestors()` on a root node will trigger a database query even though the node cannot have ancestors. 
This change makes the behaviour consistent with what [NS_Tree](https://github.com/django-treebeard/django-treebeard/blob/ad44d91d0459750278694c49ed8e9525ff3089ee/treebeard/ns_tree.py#L631-L632) does, and skips the database query if the node is a root node.
> Prevent unnecessary database query for get_ancestors() on MP_Tree if the node is a root node

- docs/source/tests.rst
Since the removal of requirements_test.txt (in 2a0e8fb756d7c9dfce5f66e2b3cf68274dbc96d5 and 63610e0fd83d2fbb4126963bbe22b5b0a76f6104) it is no longer the case that `pip install -r requirements.txt` will install pytest.
> Fix pytest installation instructions

- treebeard/static/treebeard/treebeard-admin.js
There is a small typo in treebeard/static/treebeard/treebeard-admin.js.
Should read `property` rather than `proprt`.
> docs: Fix simple typo, proprt -> property

- treebeard/mp_tree.py
- treebeard/tests/test_treebeard.py
This avoids strange behaviours in post_save receivers
since if the parent is in an inconsistent state many types
of queries depending on numchild does not work correctly
> Ensure post_save is triggered after parent is updated in add_child

- setup.py
- treebeard/admin.py
- treebeard/al_tree.py
- treebeard/forms.py
- treebeard/mp_tree.py
- treebeard/ns_tree.py
- treebeard/tests/urls.py
- Use simplified `super()` calls now that we've dropped Python 2 support.
- Replace use of deprecated `django.conf.urls.url` with `django.urls.path`.
> Code cleanups for Python 3 and Django > 2.2

- treebeard/mp_tree.py
- treebeard/tests/models.py
- treebeard/tests/test_treebeard.py
From [the `MP_Node.fix_tree` docs](https://django-treebeard.readthedocs.io/en/latest/mp_tree.html#treebeard.mp_tree.MP_Node.fix_tree):
> That needs complex in-place tree reordering, not available at the moment (hint: patches are welcome).
It might have taken 11 years, but I took the hint. :-)
This replaces `MP_Node.fix_tree(destructive=True)` with an implementation that non-destructively fixes 'holes' in paths and applies `node_order_by` ordering. It runs after the old `fix_tree` code has fixed up the `depth` and `numchild` values, and works pretty much as you'd expect:
* for each non-leaf node in the tree, fetch the child nodes in `node_order_by` order if specified, or `path` order if not; enumerating this queryset gives us the desired final path positions
* build a lookup table of the …
> Implement a non-destructive path-fixing algorithm for MP_Node.fix_tree

- README.rst
- appveyor.yml
- tox.ini
- treebeard/tests/settings.py
https://github.com/ESSolutions/django-mssql-backend is a fork of `django-pyodbc-azure` which supports newer versions of Django, and should let us reinstate the CI tests for MSSQL.
> Add back CI tests for MSSQL.

- CHANGES
- treebeard/__init__.py
Preparing a 4.4 release which declares support for Django 2.2 and higher, and drops support for Django 2.1 and lower, and Python 3.5 and lower.
Also fixes #169.
> Prepare version 4.4

- README.md
There was a typo in the previous URL, `https://https://pypi.python.org/pypi/django-treebeard`. Without the typo it redirects to `https://pypi.org/project/django-treebeard/` so I updated the badge to point directly there.
> Fix PyPI badge URL in README

- tox.ini
- treebeard/al_tree.py
- treebeard/forms.py
- treebeard/mp_tree.py
- treebeard/ns_tree.py
- treebeard/tests/models.py
- treebeard/tests/test_treebeard.py
treebeard was expecting the primary key for models to be integer serials
fixed two problems
1) detection of insertion was checking if the pk was None, but with custom ids with default values (as with uuids) the pk is never None as the default is set at model init. changed all checks to use more reliable `model._state.adding` instead.
2) the forms forced the use of integer as reference id, so it triggered an error when sending an uuid. I used the model field's formfield `to_python` as coerce function if applicable.
I also added tests but let me know if I should add more tests.
> allow working with custom ids

- treebeard/al_tree.py
- treebeard/forms.py
- treebeard/models.py
- treebeard/mp_tree.py
- treebeard/ns_tree.py
- treebeard/templatetags/admin_tree_list.py
- treebeard/tests/models.py
- treebeard/tests/test_treebeard.py
Models don't always have their pk in a column labeled 'id'. This addition allows for alternative pk column names.
> Alternative pk field name

- treebeard/mp_tree.py
This was necessary for old versions of Python when treebeard was originally written, but all the currently supported versions include a more compliant version of sqlite.
Solves #198
> Removed sqlite specific workaround.

- .github/workflows/test.yml
This adds a Github Actions workflow that (currently) does nothing - in order to get actions working for the repo. Once this is merged I'll work on moving the CI tests from Travis (see #214), which will need a bit of trial and error to get working.
> Add stub github action, to which we'll move CI tests.

- .travis.yml
- docs/source/tests.rst
- setup.py
- Add Python 3.9 to the supported Python versions in setup.py (this is needed to make the package available for that version of Python from PyPi).
- Fix up documentation for running tests.
> Declare support for Python 3.9

- treebeard/models.py
When I build the documentation of my model which inherits from `Node` with sphinx and the `:inherited-members:` included, I get the following warning:
```
/path/to/django/models/tree_node_model.py:docstring of treebeard.models.Node.get_sorted_pos_queryset:2:
WARNING: Field list ends without a blank line; unexpected unindent.
```
and it is rendered as follows:
While with my patch, the warning is gone and the documentation looks like this:
Since this is such a minor problem and trivial fix, I didn't open an issue for it, but I can do so if you prefer.
Thanks in advance for your feedback!
> Fix indentation in docstring of `get_sorted_pos_queryset`

- treebeard/exceptions.py
- treebeard/ns_tree.py
- treebeard/static/treebeard/treebeard-admin.js
- treebeard/templatetags/admin_tree.py
- treebeard/tests/test_treebeard.py
There are small typos in:
- treebeard/exceptions.py
- treebeard/ns_tree.py
- treebeard/static/treebeard/treebeard-admin.js
- treebeard/templatetags/admin_tree.py
- treebeard/tests/test_treebeard.py
Fixes:
- Should read `unchanged` rather than `unchaged`.
- Should read `tooltip` rather than `tooltop`.
- Should read `structure` rather than `strucure`.
- Should read `query string` rather than `querstring`.
- Should read `dropping` rather than `droping`.
- Should read `children` rather than `childrens`.
- Should read `attempting` rather than `attemping`.
- Should read `analyze` rather than `analize`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: Fix a few typos

- treebeard/forms.py
- treebeard/tests/test_treebeard.py
Since there weren't any updates on #177 for exactly one year now, I decided to contribute the requested changes to that PR (see https://github.com/django-treebeard/django-treebeard/pull/177#issuecomment-761757727).
The new test case should fail on the current master branch and succeed after the patch has been applied.
Since there wasn't an "unreleased" section or similar in the [CHANGES.md](https://github.com/django-treebeard/django-treebeard/blob/master/CHANGES.md), I didn't know whether to include a notice there. But if you want, I can of course add this.
Thanks in advance for your feedback!
Fixes: #176, closes #177.
> Save already constructed instance in MoveNodeForm

- docs/source/mp_tree.rst
- Describe steps for changing max_length of path field.
- Remove redundant workarounds for auto_now and auto_now_add.
Closes #149.
> Update mp-tree documentation for modern versions of Django

- CHANGES.md
- treebeard/models.py
- treebeard/mp_tree.py
- treebeard/ns_tree.py
- treebeard/tests/test_treebeard.py
- Return the number of objects deleted and a dictionary with the number of deletions per object type, consistent with what Django does.
- Accept aribitrary arguments to the delete() method to support overridden models and Django's own `using` and `keep_parents` arguments.
- Set `alters_data` and `queryset_only` attributes on delete methods, to prevent them being used in an unwanted context.
I wonder whether this is enough of an API change that we need to do a major release rather than minor - open to input on this.
Fixes #197, fixes #61, fixes #160.
> Update node delete() methods to match Django's delete API.

- treebeard/mp_tree.py
- treebeard/tests/test_treebeard.py
Fixes https://github.com/django-treebeard/django-treebeard/issues/268 and adds a test case.
> Stop MP_Node.get_descendants from querying the db on leaf nodes

- docs/source/ns_tree.rst
This just updates the link to refer to the 2nd edition of the book.
Searched here: https://www.elsevier.com/search-results?query=trees%20and%20hierarchies
1st edition: https://shop.elsevier.com/books/joe-celkos-trees-and-hierarchies-in-sql-for-smarties/celko/978-1-55860-920-4
2nd edition: https://shop.elsevier.com/books/joe-celkos-trees-and-hierarchies-in-sql-for-smarties/celko/978-0-12-387733-8
> Update to link to 2nd edition of SQL for Smarties

- treebeard/static/treebeard/treebeard-admin.js
- treebeard/templates/admin/tree_change_list_results.html
It's not clear why this needed to be inline in the first place. Inline scripts can't be used with a strong CSP policy.
> CSP compatibility: don't use inline scripts

- .github/workflows/test.yml
- README.md
- setup.py
- tox.ini
Tests pass on Python 3.12 and Django 5.0
> Python 3.12 and Django 5.0 support

- treebeard/static/treebeard/treebeard-admin.js
- treebeard/templates/admin/tree_change_list.html
This removes the cookie parsing snippet in favor of fetching the CSRF token from the `currentScript` node to allow usage of `CSRF_COOKIE_HTTPONLY = True`
See also: #92
> Fix: Allow usage of CSRF_COOKIE_HTTPONLY

- treebeard/mp_tree.py
- treebeard/tests/migrations/0001_initial.py
- treebeard/tests/models.py
- treebeard/tests/test_treebeard.py
Fixes https://github.com/django-treebeard/django-treebeard/issues/219.
The qset needed to be ordered to ensure parents are serialized before the children. Otherwise a child might come first and the lnk would not have the parent and raise a KeyError, like:
```
Traceback (...):
...
File "tree/models/level.py", line 309, in dump_bulk
result = super().dump_bulk(parent, keep_ids=keep_ids)
File "treebeard/mp_tree.py", line 661, in dump_bulk
parentobj = lnk[parentpath]
KeyError: '00IW'
```
---
This was initially https://github.com/django-treebeard/django-treebeard/pull/302
> Fix KeyError in MP_Node.dump_bulk if ordering differs from depth, path

- treebeard/mp_tree.py
There was an integer ClassVar on MP_Node called `gap`. It doesn't do anything and is completely undocumented, from what I can tell.
Perhaps there was some intention to leaves gaps in the materialized path so that efficient insertions could be done without rewriting the tree?
> remove MP_Node.gap ClassVar

- treebeard/templates/admin/tree_change_list_results.html
fixes #314 by converting `node_id` and `parent_id` to string so that `1.234` is interpreted properly as integer `1234` and not as decimal `1.234`
Bug description: in listview user is not able to collapse parent if a child had id > 999 and I assume same for `parent_id`
> fix collapsible for parent or node id 999

- treebeard/al_tree.py
- treebeard/models.py
- treebeard/mp_tree.py
- treebeard/ns_tree.py
- treebeard/tests/test_treebeard.py
When working with Wagtail (which uses treebeard's `MP_Node` quite extensively) I got annoyed that Django's builtin `refresh_from_db()` didn't always work: sometimes, `get_parent()` would report the wrong parent for a model instance, even after that instance had been refreshed.
I dug a little in the codebase and found that it wasn't too hard to fix so here's a PR. Let me know if you'd like me to open an issue also.
Thanks!
> Clear cached attributes on refresh_from_db()
